{ BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },

{ BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR },

{ BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR },

{ BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR,
  HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR },

{ BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR,
  HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR },

{ BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR },

{ BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR },

{ BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, HSK_CLR, HSK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, HSK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },