{ BLK_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR,
  SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, BLK_CLR },

{ BLK_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR,
  SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, SET_CLR, BLK_CLR },

{ BLK_CLR, SET_CLR, SET_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },
 
{ BLK_CLR, SET_CLR, SET_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },
 
{ BLK_CLR, SET_CLR, SET_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },
 
{ BLK_CLR, SET_CLR, SET_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },
 
{ BLK_CLR, SET_CLR, SET_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR,
  BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR, BLK_CLR },
